version: "3"
services:
  flask:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    tty: true
    ports:
    - 8080:8080
    volumes:
    - type: bind
      source: ./app
      target: /usr/src/app